spring.application.name=royal-wedding

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://dpg-d9d1rv6rnols73cmcmlg-a.virginia-postgres.render.com:5432/royal_wedding_db
spring.datasource.username=user
spring.datasource.password=tLG8YGkG0aKGi56qFbMufZSbLq18T0Re
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Server Configuration
server.port=8080

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Hikari Connection Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.max-lifetime=1800000